language: haskell

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc-4.8 g++-4.8 c2hs
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - cabal install --only-dependencies --enable-tests

ghc:
  - 7.8

script:
  - gcc --version
  - cabal configure --enable-tests  -finternal-tests
  - cabal build
  - cabal test
